---
title: "`r params$title`"
author: "Christophe Bruley"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
    code_folding: "hide"
  word_document: 
    fig_height: 5
  html_document:
    number_sections: yes
    toc: yes
    code_folding: "hide"
params:
  title: "(UPS_10Concentration)"
  input_directory: 'data/UPS_10Concentrations/20191216/spec_sumion_sum'
  proteins_sheet_index: 4
  peptides_sheet_index: 7
  ions_sheet_index: 5
  flags_accession_regexp: !r list(ups='HUMAN_UPS', background='_YEAS|_yeas')
  abundance_column_regexp: '^abundance'
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(matrixcalc)
library(openxlsx)
library(rmdformats)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```


```{r read_data}

source('R/commons_functions.R')
source('R/file-utils.R')

file = list.files(path = params$input_directory, pattern = ".*\\.xlsx")[1]
all.proteins = NULL
ions.summary = NULL
proteins.summary = NULL
peptides.summary = NULL

```


# Parameters 

Parameters used to generate this report : 
`r knitr::kable(knit_params_as_dataframe(params))`

Detected data files to process: `r paste0(file)`

# Comparison `r file`

```{r }
filename = paste(params$input_directory, file ,sep = '/')

sheet.names = openxlsx::getSheetNames(filename)

proline.ions = openxlsx::read.xlsx(filename, sheet = params$ions_sheet_index, colNames = TRUE, startRow = 0)
proline.ions = cleanup_ions_dataset(proline.ions, params$abundance_column_regexp)
proline.ions = flag_by_accession(proline.ions, params$flags_accession_regexp)
proline.ions = replace_zero_by_na(proline.ions, params$abundance_column_regexp)

```

```{r child="dataset_summary.Rmd" }
```


# Expected vs Observed Ratios

```{r ratios}

conditions = c("10amol", "50amol", "100amol", "250amol", "500amol", "1fmol", "5fmol", "10fmol", "25fmol", "50fmol")
columns = group_columns_by_conditions(proline.proteins, conditions , params$abundance_column_regexp)
column.other.indexes = which(!(colnames(proline.proteins) %in% list.flatten(columns)))

ups.proteins = proline.proteins[which(proline.proteins$flag == 'ups'),]

ratios = ratios_analysis(ups.proteins, columns)
ups.ratios = select(ratios, "accession", starts_with("ratio"))

library(reshape2)
ups.ratios.melted = melt(ups.ratios, id.vars="accession")
means = ups.ratios.melted %>% group_by(variable) %>% summarize(mean_observed = mean(value, na.rm = TRUE))

expected = c(12.28771238,9.965784285,8.965784285,7.64385619,6.64385619,5.64385619,3.321928095,2.321928095,1)
means = cbind(means, expected)
ups.ratios.melted$expected = rep(expected, each = nrow(ups.ratios))

ggplot(ups.ratios.melted, aes(x = expected, y = value, colour = variable )) +
  geom_point() +
  geom_point(data = means, aes(x = expected, y = mean_observed), size = 2, color = "gray38") +
  geom_abline(intercept =0 , slope = 1, linetype = "12") +
  xlim(0,15) +
  scale_y_continuous(breaks = seq(0, 15, by = 1), limits = c(0,15))

```